apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-management
  namespace: argocd
  labels:
    name: argo-management
spec:
  project: default

  source:
    repoURL: https://gitlab.com/silicon2/infrastructure-projects/argocd/argocd-helm-chart.git
    path: argo-management
    targetRevision: HEAD

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd

  syncPolicy:
    automated: {}
