{{- range $repo := .Values.repositories }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $repo }}-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    vault.security.banzaicloud.io/vault-addr: 'https://vault.default:8200'
    vault.security.banzaicloud.io/vault-agent: 'false'
    vault.security.banzaicloud.io/vault-path: kubernetes
    vault.security.banzaicloud.io/vault-role: vault-secrets-webhook
    vault.security.banzaicloud.io/vault-skip-verify: 'true'
stringData:
  name: {{ $repo }}-repo
  project: default
  type: git
  url: vault:secrets/data/argocd/repositories/{{ $repo }}#url
  password: vault:secrets/data/argocd/repositories/{{ $repo }}#password
---
{{- end }}
