{{- $url := .Values.url }}
{{- $access := .Values.access }}
{{- range $secret := .Values.secrets }}
{{- range $ns := $secret.namespaces }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: {{ $ns }}
  annotations:
    vault.security.banzaicloud.io/vault-addr: {{ $url }}
    vault.security.banzaicloud.io/vault-agent: "false"
    vault.security.banzaicloud.io/vault-role: "webhook"
    vault.security.banzaicloud.io/vault-skip-verify: "true"
    vault.security.banzaicloud.io/vault-path: {{ $access }}
type: Opaque
stringData:
{{ toYaml $secret.data | indent 2 }}
---
{{- end }}
{{- end }}
