access: "prod-kubernetes"
url: "https://vault.default:8200"
secrets:
  - name: prod-apitest-secret
    namespaces:
      - test
    data:
      CLIENT_CRT: vault:secrets/data/prod/k8s-secrets/apitest#CLIENT_CRT
      CLIENT_KEY: vault:secrets/data/prod/k8s-secrets/apitest#CLIENT_KEY
